import { HOME } from "@/lib/content";
import { img } from "@/lib/images";
import { Container } from "@/components/ui/Container";
import { Button } from "@/components/ui/Button";

/**
 * Homepage hero.
 *
 * The grid break on this page: the headline block sits in the left two thirds
 * over a full-bleed image, and the trust bar below breaks out of the container
 * to run full width against the marsh surface. One departure from the
 * container, not three. See CLAUDE.md section 7.
 *
 * -----------------------------------------------------------------------------
 * WHY THIS ONE IMAGE IS NOT next/image
 * -----------------------------------------------------------------------------
 * docs/image-prompts.md specifies two different photographs here, not two crops:
 * "Not a crop of the desktop hero. A vertical frame needs a vertical subject."
 *
 * That is art direction, and it needs a <picture> element with media queries so
 * the browser picks the frame before it fetches anything. A <picture> bypasses
 * the next/image optimizer, so the AVIF and WebP files are pre-generated by
 * scripts/hero-formats.mjs and referenced directly, with the JPEG as the final
 * fallback. That ordering gives format negotiation and art direction together,
 * and exactly one photograph is ever downloaded.
 *
 * An earlier version wrapped next/image in a <picture>. It rendered at the
 * intrinsic 2560px width and forced 2,568px of horizontal scroll on a phone.
 * The two approaches do not combine.
 */

export function Hero() {
  const desktop = img("hero-desktop");
  const mobile = img("hero-mobile");

  return (
    // -mt pulls the section up under the sticky header so the photograph runs
    // behind the transparent nav. The inner padding below already clears it.
    <section className="relative -mt-[72px] md:-mt-[84px]">
      <div className="absolute inset-0 -z-10 overflow-hidden bg-marsh-deep">
        {/*
          The <picture> carries the sizing. It defaults to display:inline, so
          left as-is it participates in layout at the image's intrinsic width
          and forces horizontal scroll. Making it the absolutely positioned box
          and letting the <img> simply fill it keeps the intrinsic dimensions
          out of layout entirely.
        */}
        <picture className="absolute inset-0 block h-full w-full">
          {/* Desktop frame: the street scene. Chosen above 768px. */}
          <source media="(min-width: 768px)" type="image/avif" srcSet={`${desktop.src.replace(/\.jpg$/, ".avif")}`} />
          <source media="(min-width: 768px)" type="image/webp" srcSet={`${desktop.src.replace(/\.jpg$/, ".webp")}`} />
          <source media="(min-width: 768px)" srcSet={desktop.src} />
          {/* Mobile frame: a single vertical triple decker. */}
          <source type="image/avif" srcSet={`${mobile.src.replace(/\.jpg$/, ".avif")}`} />
          <source type="image/webp" srcSet={`${mobile.src.replace(/\.jpg$/, ".webp")}`} />
          <img
            src={mobile.src}
            alt={desktop.alt}
            width={mobile.width}
            height={mobile.height}
            fetchPriority="high"
            decoding="async"
            className="h-full w-full object-cover"
          />
        </picture>
        <div className="absolute inset-0 bg-gradient-to-r from-marsh-deep/90 via-marsh-deep/70 to-marsh-deep/25" />
        {/*
          A second scrim along the top edge only. The horizontal gradient above
          leaves the right side light, and the header sits transparent over it
          with white nav type, which failed 4.5:1 against an overcast sky. This
          darkens the top 160px across the full width so the nav clears contrast
          wherever the photograph happens to be bright.
        */}
        <div className="absolute inset-x-0 top-0 h-40 bg-gradient-to-b from-marsh-deep/75 to-transparent" />
      </div>

      <Container width="wide">
        <div className="max-w-[46rem] pb-16 pt-24 md:pb-24 md:pt-36 lg:pb-32 lg:pt-44">
          <p className="eyebrow text-oyster/60">{HOME.hero.eyebrow}</p>
          <h1 className="mt-5 text-display-xl text-white">{HOME.hero.headline}</h1>
          <p className="mt-6 max-w-prose text-body-lg text-oyster/85">
            {HOME.hero.subheadline}
          </p>
          <div className="mt-9 flex flex-wrap gap-3">
            <Button href="/free-estimate/" size="lg">
              {HOME.hero.primaryCta}
            </Button>
            <Button href="/services/" size="lg" variant="inverse">
              {HOME.hero.secondaryCta}
            </Button>
          </div>
        </div>
      </Container>

      {/* The grid break: full-width band, content still aligned to the container. */}
      <div className="border-y-hairline border-marsh-mid bg-marsh">
        <Container width="wide">
          <dl className="grid divide-y-hairline divide-marsh-mid sm:grid-cols-2 sm:divide-y-0 lg:grid-cols-4">
            {HOME.trustBar.map((item, i) => (
              <div
                key={item.label}
                className={`py-6 lg:px-6 ${i > 0 ? "lg:border-l-hairline lg:border-marsh-mid" : "lg:pl-0"} ${
                  i % 2 === 1 ? "sm:border-l-hairline sm:border-marsh-mid sm:pl-6 lg:pl-6" : ""
                }`}
              >
                <dt className="font-mono text-mono uppercase text-cranberry-light">
                  {item.label}
                </dt>
                <dd className="mt-2 text-body-sm text-oyster/70">{item.detail}</dd>
              </div>
            ))}
          </dl>
        </Container>
      </div>
    </section>
  );
}
