/**
 * cities-phase4.ts
 *
 * CRITICAL DATA FILE. Do not regenerate or bulk-rewrite. See CLAUDE.md section 4.
 *
 * PHASE 4: Massachusetts municipalities ranked approximately 51 to 150 by
 * population. 100 entries.
 *
 * ORDERING CAVEAT. Ranking is approximate, drawn from 2020 Decennial Census
 * figures. Municipalities near the rank 50 and rank 150 boundaries may be a few
 * ranks off. This affects rollout sequence only. All 351 Massachusetts
 * municipalities appear across phases 2, 4, and 5, verified by
 * scripts/validate-data.ts.
 *
 * SEQUENCING NOTE. This is the phase where Greater Boston exterior terms become
 * winnable, because by this point Rhode Island, the top 50 Massachusetts
 * cities, and all of Connecticut are indexed and the domain has authority that
 * Capital Construction Contracting does not. Lexington, Needham, Wellesley,
 * Belmont, Winchester, and Concord are their strongest towns. Publish bathroom
 * and kitchen pages there first regardless. See docs/competitors.md.
 */

import type { City } from "./cities";

export const CITIES_PHASE_4: City[] = [
  {
    slug: "lexington",
    city: "Lexington",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["02420", "02421"],
    nearbyTowns: ["Arlington", "Bedford", "Burlington", "Waltham", "Belmont", "Woburn"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "The Battle Green area holds genuinely 18th century colonials under Historic Districts Commission review, where window sash profile and siding material are regulated. The bulk of the town is 1950s and 1960s capes, garrisons, and a notable concentration of mid-century modern houses in Six Moon Hill and Peacock Farm.",
  },
  {
    slug: "franklin",
    city: "Franklin",
    state: "MA",
    county: "Norfolk County",
    zipCodes: ["02038"],
    nearbyTowns: ["Bellingham", "Medway", "Wrentham", "Norfolk", "Millis"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "The downtown holds 19th century mill and worker housing from the straw hat industry. The rest of the town grew fast from the 1980s onward, so a large share of the stock is colonials and garrisons on wooded lots now reaching first roof replacement and first exterior repaint.",
  },
  {
    slug: "milford",
    city: "Milford",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01757"],
    nearbyTowns: ["Hopedale", "Mendon", "Upton", "Holliston", "Bellingham", "Hopkinton"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Blackstone Valley",
    homeStyleNote:
      "Built on pink granite quarrying, and the local stone appears in foundations and civic buildings throughout. Dense two- and three-family housing from 1880 to 1920 near the center, with postwar capes and later colonials on the outskirts.",
  },
  {
    slug: "northampton",
    city: "Northampton",
    state: "MA",
    county: "Hampshire County",
    zipCodes: ["01060", "01062", "01053"],
    nearbyTowns: ["Easthampton", "Hadley", "Williamsburg", "Westhampton", "Hatfield"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Pioneer Valley",
    homeStyleNote:
      "Elm Street and the Smith College area hold substantial Victorians, Queen Annes, and Colonial Revivals under historic review. Florence and Leeds are 19th century mill villages, and the outlying areas hold farmhouses on the Connecticut River floodplain.",
  },
  {
    slug: "norwood",
    city: "Norwood",
    state: "MA",
    county: "Norfolk County",
    zipCodes: ["02062"],
    nearbyTowns: ["Walpole", "Westwood", "Dedham", "Canton", "Sharon"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Dense two-families and worker housing near the center from the tannery and printing era, with a large stock of 1920s colonials and postwar capes filling the rest of the town on modest lots.",
  },
  {
    slug: "needham",
    city: "Needham",
    state: "MA",
    county: "Norfolk County",
    zipCodes: ["02492", "02494"],
    nearbyTowns: ["Newton", "Wellesley", "Dedham", "Dover", "Westwood"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Largely 1920s through 1950s colonials, capes, and Colonial Revivals on well-treed lots, with heavy tear-down and rebuild activity replacing modest capes with large new colonials. Needham Heights holds denser two-family and worker housing.",
  },
  {
    slug: "tewksbury",
    city: "Tewksbury",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01876"],
    nearbyTowns: ["Lowell", "Billerica", "Wilmington", "Andover", "Dracut"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Merrimack Valley",
    homeStyleNote:
      "Predominantly postwar and later. Capes, ranches, split levels, and garrison colonials built between 1955 and 1990 on wooded lots, most now on a second roof with original or first-replacement windows still in place.",
  },
  {
    slug: "melrose",
    city: "Melrose",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["02176"],
    nearbyTowns: ["Malden", "Stoneham", "Wakefield", "Saugus", "Medford"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "A dense Victorian streetcar suburb. Queen Annes, Colonial Revivals, and two-families from 1880 to 1920 on narrow lots throughout, several districts under historic review, with heavy original detail that makes siding material choice a real question.",
  },
  {
    slug: "stoughton",
    city: "Stoughton",
    state: "MA",
    county: "Norfolk County",
    zipCodes: ["02072"],
    nearbyTowns: ["Canton", "Sharon", "Avon", "Brockton", "Randolph", "Easton"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "The center holds 19th century two-families and worker housing from the shoe industry. The rest of the town is postwar capes and ranches with 1980s and later colonial subdivisions on wooded lots.",
  },
  {
    slug: "west-springfield",
    city: "West Springfield",
    state: "MA",
    county: "Hampden County",
    zipCodes: ["01089"],
    nearbyTowns: ["Springfield", "Agawam", "Holyoke", "Chicopee", "Westfield"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Pioneer Valley",
    homeStyleNote:
      "Merrick and the riverfront hold dense two-families and worker housing from the rail and industrial era. Mittineague is a former paper mill village, and the hill sections are postwar capes and ranches on modest lots.",
  },
  {
    slug: "agawam",
    city: "Agawam",
    state: "MA",
    county: "Hampden County",
    zipCodes: ["01001", "01030"],
    nearbyTowns: ["West Springfield", "Southwick", "Westfield", "Longmeadow", "Suffield"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Pioneer Valley",
    homeStyleNote:
      "Feeding Hills and Agawam Center are largely postwar capes and ranches on former tobacco and dairy land, with 1980s and later colonials filling in. Some 18th and 19th century farmhouses survive along Main Street and River Road.",
  },
  {
    slug: "wellesley",
    city: "Wellesley",
    state: "MA",
    county: "Norfolk County",
    zipCodes: ["02481", "02482"],
    nearbyTowns: ["Newton", "Needham", "Natick", "Weston", "Dover"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "MetroWest",
    homeStyleNote:
      "Substantial Colonial Revival, Tudor revival, and shingle-style houses on large well-treed lots, many with slate or synthetic slate roofs and copper gutter where replacement is specialty work. Wellesley Hills and Babson Park hold the largest stock.",
  },
  {
    slug: "saugus",
    city: "Saugus",
    state: "MA",
    county: "Essex County",
    zipCodes: ["01906"],
    nearbyTowns: ["Lynn", "Melrose", "Revere", "Wakefield", "Malden", "Lynnfield"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "North Shore",
    homeStyleNote:
      "Predominantly postwar capes and ranches on modest lots, with older housing and two-families near Cliftondale and Saugus Center. The Saugus Iron Works area retains some genuinely 17th and 18th century structures.",
  },
  {
    slug: "danvers",
    city: "Danvers",
    state: "MA",
    county: "Essex County",
    zipCodes: ["01923"],
    nearbyTowns: ["Peabody", "Beverly", "Middleton", "Topsfield", "Salem", "Wenham"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "North Shore",
    homeStyleNote:
      "Danvers Center and Putnamville hold antique colonials and Federal houses, several 17th and 18th century including the Rebecca Nurse Homestead. The bulk of the town is 1950s and 1960s capes and ranches on wooded lots.",
  },
  {
    slug: "marshfield",
    city: "Marshfield",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02050", "02047", "02051", "02059"],
    nearbyTowns: ["Duxbury", "Scituate", "Pembroke", "Norwell", "Hanover"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "Brant Rock, Green Harbor, and Ocean Bluff hold dense converted summer cottages on small lots in direct Atlantic exposure inside mapped flood zones, many raised after repeated storm damage. Inland the stock is antique capes and postwar and later colonials.",
  },
  {
    slug: "walpole",
    city: "Walpole",
    state: "MA",
    county: "Norfolk County",
    zipCodes: ["02081", "02032"],
    nearbyTowns: ["Norwood", "Sharon", "Foxborough", "Medfield", "Dover", "Norfolk"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Walpole Center and East Walpole hold 19th century mill worker housing from the Bird and Son paper era. The rest of the town is postwar capes and 1970s through 2000s colonials on wooded lots with heavy oak leaf load.",
  },
  {
    slug: "dedham",
    city: "Dedham",
    state: "MA",
    county: "Norfolk County",
    zipCodes: ["02026"],
    nearbyTowns: ["Westwood", "Needham", "Norwood", "Milton", "Boston", "Canton"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Dedham Village holds genuinely 17th and 18th century houses including the Fairbanks House, under historic review. Oakdale and Riverdale are denser two-families and 1920s colonials, and East Dedham holds mill-era worker housing.",
  },
  {
    slug: "reading",
    city: "Reading",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01867"],
    nearbyTowns: ["Wakefield", "North Reading", "Stoneham", "Woburn", "Lynnfield", "Wilmington"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "A mix of 1920s colonials near the center and a large stock of 1950s and 1960s capes, garrisons, and split levels on wooded lots, with some antique colonials surviving along Summer Avenue and near the common.",
  },
  {
    slug: "burlington",
    city: "Burlington",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01803"],
    nearbyTowns: ["Woburn", "Bedford", "Billerica", "Wilmington", "Lexington", "Reading"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Built out almost entirely between 1955 and 1975 as Route 128 development arrived. Capes, ranches, split levels, and garrison colonials on quarter-acre lots, nearly all now on a second or third roof with aging original window units.",
  },
  {
    slug: "wilmington",
    city: "Wilmington",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01887"],
    nearbyTowns: ["Woburn", "Burlington", "Billerica", "Tewksbury", "Reading", "North Reading"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Merrimack Valley",
    homeStyleNote:
      "Predominantly postwar capes, ranches, and split levels on wooded lots, with 1980s and later colonials in the newer subdivisions. Some antique colonials survive near the town center and along Middlesex Avenue.",
  },
  {
    slug: "canton",
    city: "Canton",
    state: "MA",
    county: "Norfolk County",
    zipCodes: ["02021"],
    nearbyTowns: ["Stoughton", "Sharon", "Norwood", "Milton", "Randolph", "Dedham"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Canton Center and Ponkapoag hold 19th century mill housing and antique colonials. The bulk of the town is postwar capes and ranches with later colonials on wooded lots against the Blue Hills, where mature oak canopy drives persistent gutter debris.",
  },
  {
    slug: "hingham",
    city: "Hingham",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02043"],
    nearbyTowns: ["Cohasset", "Norwell", "Weymouth", "Scituate", "Hull"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "Main Street holds one of the finest runs of colonial and Federal houses in Massachusetts, under Historic Districts Commission review, including the 1681 Old Ship Church. Crow Point and World's End sit on direct harbor exposure, and the southern end is postwar and later.",
  },
  {
    slug: "bridgewater",
    city: "Bridgewater",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02324", "02325"],
    nearbyTowns: ["East Bridgewater", "West Bridgewater", "Raynham", "Middleborough", "Halifax"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "The center holds Federal and Greek Revival houses near the common and the university, with 19th century two-families nearby. The outlying areas are postwar capes and 1980s through 2000s colonials on former farmland and wooded lots.",
  },
  {
    slug: "gloucester",
    city: "Gloucester",
    state: "MA",
    county: "Essex County",
    zipCodes: ["01930"],
    nearbyTowns: ["Rockport", "Essex", "Manchester-by-the-Sea", "Ipswich"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "North Shore",
    homeStyleNote:
      "A working fishing port with dense clapboard and shingled housing packed on steep granite slopes around the harbor, much of it 19th century. Eastern Point and Annisquam hold shingle-style summer houses in severe salt and wind exposure where fastener corrosion is the routine failure mode.",
  },
  {
    slug: "easton",
    city: "Easton",
    state: "MA",
    county: "Bristol County",
    zipCodes: ["02356", "02334", "02375"],
    nearbyTowns: ["Stoughton", "Brockton", "Norton", "Mansfield", "Raynham", "Sharon"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "South Coast",
    homeStyleNote:
      "North Easton village holds a nationally significant group of H.H. Richardson buildings and Ames family estates in local stone, under historic review. The rest of the town is postwar capes and later colonials on wooded lots.",
  },
  {
    slug: "acton",
    city: "Acton",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01720", "01718"],
    nearbyTowns: ["Concord", "Maynard", "Boxborough", "Littleton", "Westford", "Carlisle"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "MetroWest",
    homeStyleNote:
      "Four village centers with antique colonials and 19th century mill housing, and a very large stock of 1960s through 1990s colonials, garrisons, and contemporaries on wooded acre lots where heavy tree cover drives roof moss and gutter load.",
  },
  {
    slug: "belmont",
    city: "Belmont",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["02478"],
    nearbyTowns: ["Cambridge", "Watertown", "Arlington", "Waltham", "Lexington"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Belmont Hill holds substantial Colonial Revivals and Tudor revivals on large lots. Waverley and Cushing Square are dense two-families and 1920s colonials on narrow lots where staging comes off the street.",
  },
  {
    slug: "milton",
    city: "Milton",
    state: "MA",
    county: "Norfolk County",
    zipCodes: ["02186"],
    nearbyTowns: ["Quincy", "Boston", "Dedham", "Canton", "Randolph", "Braintree"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Milton Village and Brush Hill hold Federal and Greek Revival houses, several 18th century, under historic review. East Milton is denser with two-families and 1920s colonials, and the Blue Hills side holds larger houses on wooded slopes.",
  },
  {
    slug: "westford",
    city: "Westford",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01886"],
    nearbyTowns: ["Chelmsford", "Littleton", "Groton", "Tyngsborough", "Acton", "Carlisle"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Merrimack Valley",
    homeStyleNote:
      "Westford Center and Graniteville hold antique colonials and 19th century quarry and mill worker housing. The bulk of the town is 1980s through 2000s colonials on wooded acre lots now reaching first roof replacement.",
  },
  {
    slug: "stoneham",
    city: "Stoneham",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["02180"],
    nearbyTowns: ["Melrose", "Woburn", "Reading", "Wakefield", "Winchester", "Medford"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Dense two-families and Victorians near the center from the shoe manufacturing era, with postwar capes and split levels on the wooded slopes toward the Middlesex Fells on lots where grade complicates staging.",
  },
  {
    slug: "winchester",
    city: "Winchester",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01890"],
    nearbyTowns: ["Woburn", "Arlington", "Medford", "Stoneham", "Lexington"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Substantial Colonial Revival, Tudor revival, and shingle-style houses on the wooded hills above the town center, many with slate roofs and copper flashing. The flatter sections near the center hold 1920s colonials and some two-families.",
  },
  {
    slug: "longmeadow",
    city: "Longmeadow",
    state: "MA",
    county: "Hampden County",
    zipCodes: ["01106"],
    nearbyTowns: ["Springfield", "East Longmeadow", "Enfield", "Agawam"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Pioneer Valley",
    homeStyleNote:
      "The Longmeadow green holds 18th and 19th century houses under historic review. The rest of the town is a well-preserved 1920s through 1950s suburb of Colonial Revivals, Tudors, and center-entrance colonials on mature tree-lined streets.",
  },
  {
    slug: "ludlow",
    city: "Ludlow",
    state: "MA",
    county: "Hampden County",
    zipCodes: ["01056"],
    nearbyTowns: ["Springfield", "Chicopee", "Wilbraham", "Belchertown", "Palmer"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Pioneer Valley",
    homeStyleNote:
      "The mill district along the Chicopee River holds dense worker housing built for the jute mills, much of it in intact rows. The rest of the town is postwar capes and ranches and later colonials on former farmland.",
  },
  {
    slug: "wareham",
    city: "Wareham",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02571", "02538", "02532", "02576"],
    nearbyTowns: ["Bourne", "Marion", "Carver", "Plymouth", "Rochester"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "Onset and the Buzzards Bay shoreline hold dense converted summer cottages on small lots in direct salt exposure, many inside mapped flood zones. Wareham Center holds 19th century village housing, and the inland sections are cranberry bog land with farmhouses.",
  },
  {
    slug: "north-attleborough",
    city: "North Attleborough",
    state: "MA",
    county: "Bristol County",
    zipCodes: ["02760", "02763"],
    nearbyTowns: ["Attleboro", "Plainville", "Wrentham", "Mansfield", "Cumberland"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "South Coast",
    homeStyleNote:
      "Built on the jewelry industry, with dense two-families and worker housing near the center and in Attleboro Falls. The outer sections are postwar capes and 1980s through 2000s colonials on wooded lots.",
  },
  {
    slug: "middleborough",
    city: "Middleborough",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02346", "02344"],
    nearbyTowns: ["Lakeville", "Bridgewater", "Carver", "Halifax", "Raynham", "Rochester"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "One of the largest towns by land area in the state. The center holds Federal, Greek Revival, and Victorian houses from the shovel and shoe industry era, and the outlying areas are cranberry bog land with farmhouses and scattered later subdivisions.",
  },
  {
    slug: "grafton",
    city: "Grafton",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01519", "01536", "01560"],
    nearbyTowns: ["Worcester", "Shrewsbury", "Millbury", "Northbridge", "Upton", "Westborough"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Blackstone Valley",
    homeStyleNote:
      "Grafton Common holds Federal and Greek Revival houses under historic review. Fisherville and Farnumsville are Blackstone Valley mill villages with intact worker housing, and North Grafton has substantial newer colonial subdivisions.",
  },
  {
    slug: "hudson",
    city: "Hudson",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01749"],
    nearbyTowns: ["Marlborough", "Stow", "Bolton", "Berlin", "Sudbury", "Maynard"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "MetroWest",
    homeStyleNote:
      "A shoe manufacturing town with dense two- and three-family worker housing near the Assabet River, most 1880 to 1920 on tight lots. The outer sections are postwar capes and later colonials on wooded parcels.",
  },
  {
    slug: "sudbury",
    city: "Sudbury",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01776"],
    nearbyTowns: ["Wayland", "Concord", "Framingham", "Marlborough", "Lincoln", "Hudson"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "MetroWest",
    homeStyleNote:
      "Antique colonials and saltboxes along the Boston Post Road including the Wayside Inn, under historic review. The bulk of the town is 1960s through 1990s colonials and contemporaries on wooded acre lots with heavy leaf load and long drives.",
  },
  {
    slug: "norton",
    city: "Norton",
    state: "MA",
    county: "Bristol County",
    zipCodes: ["02766"],
    nearbyTowns: ["Attleboro", "Mansfield", "Taunton", "Easton", "Rehoboth"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "South Coast",
    homeStyleNote:
      "The center holds Federal and Greek Revival houses near the common and Wheaton College. The rest of the town is postwar capes and a large stock of 1980s through 2000s colonials on wooded lots and former farmland.",
  },
  {
    slug: "mansfield",
    city: "Mansfield",
    state: "MA",
    county: "Bristol County",
    zipCodes: ["02048"],
    nearbyTowns: ["Foxborough", "Norton", "Easton", "Attleboro", "Sharon", "Norfolk"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "South Coast",
    homeStyleNote:
      "The downtown holds 19th century two-families and worker housing from the jewelry and rail era. The bulk of the town is 1970s through 2000s colonials and raised ranches on wooded lots now cycling into first and second roof replacement.",
  },
  {
    slug: "winthrop",
    city: "Winthrop",
    state: "MA",
    county: "Suffolk County",
    zipCodes: ["02152"],
    nearbyTowns: ["Revere", "Boston", "Chelsea"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "A dense peninsula town of two- and three-family housing and shingled cottages from 1900 to 1930 on very small lots, surrounded by water on three sides. Direct Atlantic and harbor exposure means salt reaches every elevation and flood zones cover much of the town.",
  },
  {
    slug: "falmouth",
    city: "Falmouth",
    state: "MA",
    county: "Barnstable County",
    zipCodes: ["02540", "02536", "02556", "02543", "02574"],
    nearbyTowns: ["Mashpee", "Bourne", "Sandwich"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Cape and Islands",
    homeStyleNote:
      "Falmouth Village and Woods Hole hold Federal, Greek Revival, and shingle-style houses under historic review. The village greens and the Vineyard Sound shoreline hold weathered cedar shingle cottages where salt spray and driving rain govern siding and fastener choices.",
  },
  {
    slug: "sandwich",
    city: "Sandwich",
    state: "MA",
    county: "Barnstable County",
    zipCodes: ["02563", "02537", "02644", "02649"],
    nearbyTowns: ["Barnstable", "Bourne", "Mashpee", "Falmouth"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Cape and Islands",
    homeStyleNote:
      "The oldest town on Cape Cod. Sandwich Village holds genuinely 17th and 18th century capes and Federal houses under Old King's Highway Historic District review north of Route 6A. Forestdale and East Sandwich are largely postwar and later capes and colonials.",
  },
  {
    slug: "yarmouth",
    city: "Yarmouth",
    state: "MA",
    county: "Barnstable County",
    zipCodes: ["02664", "02673", "02675"],
    nearbyTowns: ["Barnstable", "Dennis"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Cape and Islands",
    homeStyleNote:
      "Yarmouth Port along Route 6A holds sea captains' houses, Federal and Greek Revival, under Old King's Highway review. South Yarmouth and West Yarmouth hold dense postwar cottages and ranches built for the tourist economy, most with cedar shingle now weathered grey.",
  },
  {
    slug: "bourne",
    city: "Bourne",
    state: "MA",
    county: "Barnstable County",
    zipCodes: ["02532", "02559", "02562", "02534", "02553"],
    nearbyTowns: ["Sandwich", "Falmouth", "Wareham", "Plymouth", "Mashpee"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Cape and Islands",
    homeStyleNote:
      "Split by the Cape Cod Canal. Buzzards Bay and Sagamore hold denser village housing, while Pocasset, Cataumet, and Monument Beach hold shingled cottages and converted seasonal houses on direct Buzzards Bay exposure with high wind loading at the canal.",
  },
  {
    slug: "amesbury",
    city: "Amesbury",
    state: "MA",
    county: "Essex County",
    zipCodes: ["01913"],
    nearbyTowns: ["Merrimac", "Salisbury", "Newburyport", "West Newbury", "Haverhill"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Merrimack Valley",
    homeStyleNote:
      "A carriage manufacturing town with dense mill worker housing and two-families on the slopes above the Powow River, most 1850 to 1920. The outer sections are postwar capes and later colonials on wooded lots.",
  },
  {
    slug: "newburyport",
    city: "Newburyport",
    state: "MA",
    county: "Essex County",
    zipCodes: ["01950"],
    nearbyTowns: ["Newbury", "Amesbury", "Salisbury", "West Newbury", "Rowley"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "North Shore",
    homeStyleNote:
      "High Street holds one of the densest concentrations of Federal architecture in America, several hundred houses from the shipping era, under strict historic review governing window profile and siding. The South End and Joppa hold denser shipbuilding-era worker housing near the water.",
  },
  {
    slug: "wayland",
    city: "Wayland",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01778"],
    nearbyTowns: ["Sudbury", "Weston", "Natick", "Framingham", "Lincoln", "Concord"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "MetroWest",
    homeStyleNote:
      "Antique colonials and farmhouses near the town center and along Old Sudbury Road, plus a large stock of 1950s through 1980s colonials, capes, and contemporaries on wooded lots along the Sudbury River floodplain.",
  },
  {
    slug: "concord",
    city: "Concord",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01742", "01741"],
    nearbyTowns: ["Acton", "Lincoln", "Carlisle", "Bedford", "Sudbury", "Maynard"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "MetroWest",
    homeStyleNote:
      "Monument Street, Main Street, and Lexington Road hold genuinely 17th and 18th century houses under Historic Districts Commission review, where siding material, window sash, and even paint color are regulated. West Concord is a denser mill village, and the outlying areas hold 1950s through 1980s colonials on wooded acreage.",
  },
  {
    slug: "holliston",
    city: "Holliston",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01746"],
    nearbyTowns: ["Ashland", "Sherborn", "Medway", "Milford", "Hopkinton", "Framingham"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "MetroWest",
    homeStyleNote:
      "The center holds Greek Revival and Victorian houses from the shoe manufacturing era, with mill worker housing nearby. The rest of the town is postwar capes and 1970s through 1990s colonials on wooded acre lots.",
  },
  {
    slug: "ashland",
    city: "Ashland",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01721"],
    nearbyTowns: ["Framingham", "Holliston", "Hopkinton", "Sherborn", "Natick"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "MetroWest",
    homeStyleNote:
      "The downtown holds 19th century mill housing from the clock and shoe industries. A large share of the town is 1980s through 2000s colonials and townhouse development on wooded lots, now reaching first roof and first repaint.",
  },
  {
    slug: "hopkinton",
    city: "Hopkinton",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01748"],
    nearbyTowns: ["Ashland", "Holliston", "Milford", "Upton", "Westborough", "Southborough"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "MetroWest",
    homeStyleNote:
      "The common holds Federal and Greek Revival houses. The town grew very fast from the 1990s onward, so the dominant stock is large colonials on wooded acre lots built 1995 to 2015, now hitting first roof replacement and first exterior maintenance cycle together.",
  },
  {
    slug: "medway",
    city: "Medway",
    state: "MA",
    county: "Norfolk County",
    zipCodes: ["02053"],
    nearbyTowns: ["Millis", "Franklin", "Holliston", "Bellingham", "Medfield"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Medway Village and West Medway hold 19th century mill worker housing along the Charles. The rest of the town is postwar capes and a substantial stock of 1980s through 2000s colonials on wooded lots.",
  },
  {
    slug: "millbury",
    city: "Millbury",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01527"],
    nearbyTowns: ["Worcester", "Sutton", "Grafton", "Auburn", "Oxford"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Blackstone Valley",
    homeStyleNote:
      "A Blackstone Valley mill town with dense worker housing and two-families along the Blackstone River, most 1850 to 1920. The hill sections are postwar capes and ranches on steep wooded lots where driveway grade affects material delivery.",
  },
  {
    slug: "auburn",
    city: "Auburn",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01501"],
    nearbyTowns: ["Worcester", "Millbury", "Oxford", "Leicester", "Sutton", "Charlton"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Central Massachusetts",
    homeStyleNote:
      "Largely a postwar suburb of Worcester. Capes, ranches, and split levels from the 1950s and 1960s on modest lots, with later colonials filling in and a small stock of antique farmhouses near the town center.",
  },
  {
    slug: "webster",
    city: "Webster",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01570"],
    nearbyTowns: ["Dudley", "Oxford", "Douglas", "Thompson", "Sutton"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Central Massachusetts",
    homeStyleNote:
      "A textile mill town with dense three-deckers and worker housing along the French River, most 1880 to 1920. Webster Lake is ringed with converted seasonal cottages on small lots that were winterized without upgrading walls or roof framing.",
  },
  {
    slug: "southbridge",
    city: "Southbridge",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01550"],
    nearbyTowns: ["Sturbridge", "Charlton", "Dudley", "Sturbridge", "Woodstock"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Central Massachusetts",
    homeStyleNote:
      "Built on the American Optical works, so the center holds dense three-deckers and worker housing on steep slopes above the Quinebaug, most 1870 to 1920, with substantial Victorians on the hill above and postwar capes on the outskirts.",
  },
  {
    slug: "oxford",
    city: "Oxford",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01540", "01537"],
    nearbyTowns: ["Auburn", "Webster", "Charlton", "Sutton", "Dudley", "Millbury"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Central Massachusetts",
    homeStyleNote:
      "The center holds Federal and Greek Revival houses near the common, with 19th century mill worker housing in North Oxford. The rest of the town is postwar capes and later colonials on wooded lots.",
  },
  {
    slug: "clinton",
    city: "Clinton",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01510"],
    nearbyTowns: ["Lancaster", "Berlin", "Bolton", "Sterling", "Boylston"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Central Massachusetts",
    homeStyleNote:
      "A dense mill town built around the Lancaster Mills, with three-deckers and worker housing packed on steep streets above the Nashua River, most 1850 to 1910. Very tight lots make staging and neighbor access a routine part of scoping exterior work.",
  },
  {
    slug: "athol",
    city: "Athol",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01331"],
    nearbyTowns: ["Orange", "Phillipston", "Royalston", "Petersham", "New Salem"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Central Massachusetts",
    homeStyleNote:
      "A tool manufacturing town with dense two- and three-family worker housing on the hills above the Millers River, most 1880 to 1920. Deferred maintenance is widespread in the older stock, and snow load runs heavy on the north-facing slopes.",
  },
  {
    slug: "holden",
    city: "Holden",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01520", "01522"],
    nearbyTowns: ["Worcester", "Rutland", "Paxton", "Sterling", "West Boylston", "Princeton"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Central Massachusetts",
    homeStyleNote:
      "Jefferson and Dawson are small 19th century village centers with mill housing. The bulk of the town is postwar capes and 1970s through 2000s colonials on wooded lots, with heavy leaf load and snow accumulation on the higher ground.",
  },
  {
    slug: "spencer",
    city: "Spencer",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01562"],
    nearbyTowns: ["Leicester", "Charlton", "Brookfield", "Paxton", "East Brookfield"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Central Massachusetts",
    homeStyleNote:
      "A shoe manufacturing town with dense two- and three-family worker housing near the center, most 1870 to 1920. The outlying areas are hill farms with antique farmhouses and scattered later capes on wooded parcels.",
  },
  {
    slug: "whitman",
    city: "Whitman",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02382"],
    nearbyTowns: ["Abington", "Hanson", "East Bridgewater", "Brockton", "Rockland"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "A shoe town with dense two-families and worker cottages near the center from 1880 to 1920 on small lots, with postwar capes and ranches filling the rest of the town.",
  },
  {
    slug: "abington",
    city: "Abington",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02351"],
    nearbyTowns: ["Whitman", "Rockland", "Brockton", "Weymouth", "Holbrook", "Hanover"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "Another shoe manufacturing town with 19th century two-families and worker housing near the center, and a large stock of postwar capes and ranches plus later colonials on wooded lots.",
  },
  {
    slug: "rockland",
    city: "Rockland",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02370"],
    nearbyTowns: ["Abington", "Hanover", "Norwell", "Whitman", "Hingham", "Weymouth"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "Dense two-families and Victorians near the center from the shoe industry era, with postwar capes and ranches on the outer streets and later colonial subdivisions on the former naval air station land.",
  },
  {
    slug: "pembroke",
    city: "Pembroke",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02359"],
    nearbyTowns: ["Hanson", "Duxbury", "Marshfield", "Hanover", "Halifax", "Kingston"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "Antique capes and colonials near the center and Bryantville, plus a large stock of converted lake cottages around Oldham and Furnace ponds and postwar and later colonials on wooded lots.",
  },
  {
    slug: "scituate",
    city: "Scituate",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02066"],
    nearbyTowns: ["Cohasset", "Marshfield", "Norwell", "Hingham", "Hanover"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "Sand Hills, Minot, and Humarock hold dense shingled cottages on the most storm-exposed shoreline in Massachusetts, where houses take direct nor'easter surge and many have been raised or rebuilt to current flood elevation. Inland the stock is antique capes and postwar and later colonials.",
  },
  {
    slug: "duxbury",
    city: "Duxbury",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02332", "02331"],
    nearbyTowns: ["Marshfield", "Kingston", "Pembroke", "Plymouth", "Hanson"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "Washington Street and the Nook hold genuinely 17th and 18th century capes and Federal houses from the shipbuilding era, under historic review. The Duxbury Beach side holds shingled houses in direct Atlantic exposure, and the inland sections are postwar and later colonials on wooded lots.",
  },
  {
    slug: "norwell",
    city: "Norwell",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02061"],
    nearbyTowns: ["Hanover", "Scituate", "Hingham", "Marshfield", "Rockland", "Pembroke"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "Antique capes and colonials along Main Street and the North River, several 18th century, plus a large stock of 1960s through 1990s colonials and contemporaries on wooded acre lots with heavy oak and pine canopy.",
  },
  {
    slug: "hanover",
    city: "Hanover",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02339"],
    nearbyTowns: ["Norwell", "Rockland", "Pembroke", "Hanson", "Abington", "Scituate"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "Antique capes and colonials near the center and the North River shipbuilding sites, with the bulk of the town built out in postwar capes and 1970s through 1990s colonials on wooded lots.",
  },
  {
    slug: "kingston",
    city: "Kingston",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02364"],
    nearbyTowns: ["Plymouth", "Duxbury", "Pembroke", "Halifax", "Carver", "Plympton"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "The Jones River area holds antique capes and Federal houses from the shipbuilding era. Rocky Nook holds converted shoreline cottages on Kingston Bay exposure, and the rest of the town is postwar and later colonials on wooded lots.",
  },
  {
    slug: "swansea",
    city: "Swansea",
    state: "MA",
    county: "Bristol County",
    zipCodes: ["02777"],
    nearbyTowns: ["Somerset", "Fall River", "Seekonk", "Rehoboth", "Warren"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Coast",
    homeStyleNote:
      "Antique capes and farmhouses along the older roads, with converted shoreline cottages on Mount Hope Bay at Ocean Grove and Touisset that take direct southwest wind and salt exposure. The rest is postwar capes and later colonials.",
  },
  {
    slug: "somerset",
    city: "Somerset",
    state: "MA",
    county: "Bristol County",
    zipCodes: ["02725", "02726"],
    nearbyTowns: ["Swansea", "Fall River", "Dighton", "Berkley", "Rehoboth"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Coast",
    homeStyleNote:
      "Predominantly postwar capes and ranches built for the power plant and Fall River workforce, on modest lots. Older colonials and Victorians survive along Main Street and County Street near the Taunton River.",
  },
  {
    slug: "seekonk",
    city: "Seekonk",
    state: "MA",
    county: "Bristol County",
    zipCodes: ["02771"],
    nearbyTowns: ["Rehoboth", "Swansea", "Attleboro", "East Providence", "Pawtucket"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Coast",
    homeStyleNote:
      "Effectively a Providence suburb across the state line. Antique farmhouses along the older roads and a large stock of postwar capes and ranches plus later colonials on wooded and open lots.",
  },
  {
    slug: "rehoboth",
    city: "Rehoboth",
    state: "MA",
    county: "Bristol County",
    zipCodes: ["02769"],
    nearbyTowns: ["Seekonk", "Swansea", "Attleboro", "Norton", "Dighton", "Taunton"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Coast",
    homeStyleNote:
      "A rural farming town with 18th and 19th century farmhouses and center chimney colonials on large parcels along the old county roads, plus later colonials and ranches on wooded acreage with well and septic throughout.",
  },
  {
    slug: "fairhaven",
    city: "Fairhaven",
    state: "MA",
    county: "Bristol County",
    zipCodes: ["02719"],
    nearbyTowns: ["New Bedford", "Acushnet", "Mattapoisett", "Dartmouth"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Coast",
    homeStyleNote:
      "The center holds an unusual group of Rogers-funded Gothic and Romanesque civic buildings alongside whaling-era Federal and Greek Revival houses. Sconticut Neck and West Island hold converted cottages in direct Buzzards Bay exposure inside flood zones.",
  },
  {
    slug: "westport",
    city: "Westport",
    state: "MA",
    county: "Bristol County",
    zipCodes: ["02790"],
    nearbyTowns: ["Dartmouth", "Fall River", "Tiverton", "Little Compton"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Coast",
    homeStyleNote:
      "One of the largest towns by land area on the South Coast. Working farms with 18th and 19th century farmhouses and stone walls inland, and shingled cottages and larger houses at Westport Point and Horseneck Beach in severe salt and wind exposure.",
  },
  {
    slug: "raynham",
    city: "Raynham",
    state: "MA",
    county: "Bristol County",
    zipCodes: ["02767"],
    nearbyTowns: ["Taunton", "Bridgewater", "Easton", "Norton", "Middleborough", "Lakeville"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Coast",
    homeStyleNote:
      "Largely postwar and later. Capes, ranches, and a substantial stock of 1980s through 2000s colonials on wooded lots, with antique farmhouses surviving along Broadway and the older roads.",
  },
  {
    slug: "east-bridgewater",
    city: "East Bridgewater",
    state: "MA",
    county: "Plymouth County",
    zipCodes: ["02333"],
    nearbyTowns: ["Bridgewater", "West Bridgewater", "Whitman", "Hanson", "Brockton", "Halifax"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "South Shore",
    homeStyleNote:
      "Antique capes and Greek Revival houses near the center and Elmwood, with 19th century worker housing from the shovel and nail works. The rest of the town is postwar capes and later colonials on wooded lots.",
  },
  {
    slug: "palmer",
    city: "Palmer",
    state: "MA",
    county: "Hampden County",
    zipCodes: ["01069", "01080", "01009", "01079"],
    nearbyTowns: ["Ware", "Monson", "Wilbraham", "Ludlow", "Brimfield", "Belchertown"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Pioneer Valley",
    homeStyleNote:
      "Four villages: Palmer, Three Rivers, Thorndike, and Bondsville, each built around a mill on the Ware or Quaboag rivers with intact rows of 19th century worker housing. The rest of the town is farmhouses and later houses on wooded hillsides.",
  },
  {
    slug: "easthampton",
    city: "Easthampton",
    state: "MA",
    county: "Hampshire County",
    zipCodes: ["01027"],
    nearbyTowns: ["Northampton", "Southampton", "Holyoke", "Westhampton", "Hadley"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Pioneer Valley",
    homeStyleNote:
      "A button and textile mill city with dense worker housing and two-families near the mill pond, most 1860 to 1920, plus Victorians on the higher streets and postwar capes on the outskirts against Mount Tom.",
  },
  {
    slug: "south-hadley",
    city: "South Hadley",
    state: "MA",
    county: "Hampshire County",
    zipCodes: ["01075", "01034"],
    nearbyTowns: ["Holyoke", "Chicopee", "Granby", "Hadley", "Amherst"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Pioneer Valley",
    homeStyleNote:
      "The college area holds Victorians and Colonial Revivals on tree-lined streets. South Hadley Falls is a dense mill village with worker housing along the Connecticut River, and the rest of the town is postwar capes and later colonials.",
  },
  {
    slug: "greenfield",
    city: "Greenfield",
    state: "MA",
    county: "Franklin County",
    zipCodes: ["01301", "01302"],
    nearbyTowns: ["Deerfield", "Montague", "Bernardston", "Gill", "Shelburne", "Colrain"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Pioneer Valley",
    homeStyleNote:
      "The commercial center of Franklin County. Main Street holds Federal and Victorian houses under historic review, with dense two-families and worker housing from the tap and die industry nearby, and postwar capes on the outer streets.",
  },
  {
    slug: "belchertown",
    city: "Belchertown",
    state: "MA",
    county: "Hampshire County",
    zipCodes: ["01007"],
    nearbyTowns: ["Amherst", "Granby", "Ware", "Palmer", "Pelham", "Ludlow"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Pioneer Valley",
    homeStyleNote:
      "The common holds Federal and Greek Revival houses. Much of the town borders Quabbin Reservoir watershed land, and the housing stock is antique farmhouses plus a large run of 1980s through 2000s colonials on wooded acre lots.",
  },
  {
    slug: "ware",
    city: "Ware",
    state: "MA",
    county: "Hampshire County",
    zipCodes: ["01082"],
    nearbyTowns: ["Palmer", "Belchertown", "Hardwick", "Warren", "Brookfield"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Central Massachusetts",
    homeStyleNote:
      "A textile mill town with dense brick mill buildings and rows of worker housing along the Ware River, most 1850 to 1910. The outlying areas are hill farms with antique farmhouses on large wooded parcels.",
  },
  {
    slug: "wilbraham",
    city: "Wilbraham",
    state: "MA",
    county: "Hampden County",
    zipCodes: ["01095"],
    nearbyTowns: ["Springfield", "Ludlow", "Hampden", "Palmer", "East Longmeadow", "Monson"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Pioneer Valley",
    homeStyleNote:
      "Main Street holds antique colonials and Federal houses, several 18th century. The bulk of the town is 1950s through 1990s colonials, capes, and split levels on wooded lots climbing the Wilbraham Mountain ridge.",
  },
  {
    slug: "east-longmeadow",
    city: "East Longmeadow",
    state: "MA",
    county: "Hampden County",
    zipCodes: ["01028"],
    nearbyTowns: ["Longmeadow", "Springfield", "Hampden", "Wilbraham", "Enfield"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Pioneer Valley",
    homeStyleNote:
      "Built on brownstone quarrying, and the local red sandstone appears in foundations and civic buildings. The bulk of the housing is postwar capes and ranches plus later colonials on modest lots.",
  },
  {
    slug: "north-adams",
    city: "North Adams",
    state: "MA",
    county: "Berkshire County",
    zipCodes: ["01247"],
    nearbyTowns: ["Adams", "Williamstown", "Clarksburg", "Florida", "Savoy"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Berkshires",
    homeStyleNote:
      "A former mill city in a steep valley, with dense worker housing and two- and three-families climbing the hillsides, most 1870 to 1920. Among the heaviest snow loads in Massachusetts, and steep drives make winter access a real scheduling factor.",
  },
  {
    slug: "lunenburg",
    city: "Lunenburg",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01462"],
    nearbyTowns: ["Fitchburg", "Leominster", "Shirley", "Townsend", "Ashby", "Lancaster"],
    populationTier: "tiny",
    phase: 4,
    subServiceLive: false,
    region: "Central Massachusetts",
    homeStyleNote:
      "Antique capes and farmhouses near the center and along the old roads, with converted cottages around Lake Whalom and a substantial stock of postwar and later colonials on wooded lots.",
  },
  {
    slug: "northborough",
    city: "Northborough",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01532"],
    nearbyTowns: ["Westborough", "Marlborough", "Shrewsbury", "Berlin", "Southborough", "Boylston"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Central Massachusetts",
    homeStyleNote:
      "The center holds Federal and Greek Revival houses along Main Street. The rest of the town is postwar capes and a large stock of 1980s through 2000s colonials on wooded lots along the Route 9 and Route 20 corridors.",
  },
  {
    slug: "westborough",
    city: "Westborough",
    state: "MA",
    county: "Worcester County",
    zipCodes: ["01581"],
    nearbyTowns: ["Northborough", "Shrewsbury", "Grafton", "Hopkinton", "Southborough", "Upton"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "Central Massachusetts",
    homeStyleNote:
      "The center holds Victorian and Colonial Revival houses from the shoe and straw industry era. The bulk of the town is 1970s through 2000s colonials and townhouse development built during the Route 495 technology expansion.",
  },
  {
    slug: "north-reading",
    city: "North Reading",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01864"],
    nearbyTowns: ["Reading", "Wilmington", "Andover", "Middleton", "Lynnfield", "Wakefield"],
    populationTier: "tiny",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Antique capes and colonials near the town center and along Park Street, with the bulk of the town built out in postwar capes, ranches, and split levels on wooded lots plus later colonial subdivisions.",
  },
  {
    slug: "wakefield",
    city: "Wakefield",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01880"],
    nearbyTowns: ["Melrose", "Stoneham", "Reading", "Lynnfield", "Saugus", "North Reading"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Greater Boston",
    homeStyleNote:
      "Dense Victorians, Colonial Revivals, and two-families around Lake Quannapowitt and the center, most 1880 to 1925 on narrow lots. The Greenwood and Montrose sections hold postwar capes and later colonials.",
  },
  {
    slug: "lynnfield",
    city: "Lynnfield",
    state: "MA",
    county: "Essex County",
    zipCodes: ["01940"],
    nearbyTowns: ["Wakefield", "Peabody", "Saugus", "North Reading", "Lynn", "Middleton"],
    populationTier: "tiny",
    phase: 4,
    subServiceLive: false,
    region: "North Shore",
    homeStyleNote:
      "Largely a 1950s through 1970s suburb of colonials, garrisons, and split levels on wooded lots, with antique colonials preserved around the Lynnfield Common and along Main Street.",
  },
  {
    slug: "marblehead",
    city: "Marblehead",
    state: "MA",
    county: "Essex County",
    zipCodes: ["01945"],
    nearbyTowns: ["Salem", "Swampscott", "Beverly", "Lynn"],
    populationTier: "small",
    phase: 4,
    subServiceLive: false,
    region: "North Shore",
    homeStyleNote:
      "Old Town holds one of the densest concentrations of pre-1800 houses in America, packed on narrow winding streets under historic review, where access for staging is genuinely difficult. The Neck holds shingle-style summer houses in full Atlantic exposure.",
  },
  {
    slug: "swampscott",
    city: "Swampscott",
    state: "MA",
    county: "Essex County",
    zipCodes: ["01907"],
    nearbyTowns: ["Marblehead", "Salem", "Lynn", "Nahant"],
    populationTier: "tiny",
    phase: 4,
    subServiceLive: false,
    region: "North Shore",
    homeStyleNote:
      "Shingle-style and Colonial Revival houses on the slopes above the ocean, many from the resort era, plus denser two-families near the Lynn line. Direct Atlantic exposure on the eastern elevations drives paint and fastener choices.",
  },
  {
    slug: "ipswich",
    city: "Ipswich",
    state: "MA",
    county: "Essex County",
    zipCodes: ["01938"],
    nearbyTowns: ["Rowley", "Essex", "Hamilton", "Topsfield", "Gloucester", "Newbury"],
    populationTier: "tiny",
    phase: 4,
    subServiceLive: false,
    region: "North Shore",
    homeStyleNote:
      "Holds more First Period houses, pre-1725, than any other community in the country, concentrated on High Street and East Street under strict historic review. Great Neck and Little Neck hold shoreline cottages in direct exposure on Plum Island Sound.",
  },
  {
    slug: "north-andover",
    city: "North Andover",
    state: "MA",
    county: "Essex County",
    zipCodes: ["01845"],
    nearbyTowns: ["Andover", "Lawrence", "Methuen", "Boxford", "Middleton", "Haverhill"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Merrimack Valley",
    homeStyleNote:
      "The Old Center holds 17th and 18th century houses around the common under historic review. Machine Shop Village is an intact mill worker district, and the rest of the town is postwar capes and later colonials on wooded lots.",
  },
  {
    slug: "dracut",
    city: "Dracut",
    state: "MA",
    county: "Middlesex County",
    zipCodes: ["01826"],
    nearbyTowns: ["Lowell", "Tewksbury", "Methuen", "Tyngsborough", "Andover"],
    populationTier: "medium",
    phase: 4,
    subServiceLive: false,
    region: "Merrimack Valley",
    homeStyleNote:
      "Collinsville and Navy Yard hold denser mill-adjacent housing near the Lowell line. The rest of the town is postwar capes and ranches plus later colonials on former farmland, with some antique farmhouses along the older roads.",
  },
];
